name: NodeJS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  NODE_VERSION: "20.x.x"

jobs:
  test:
    # environment: dev # Specify the development environment
    runs-on: ubuntu-latest # [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  start-server:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Conditionally Start Server
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Starting server..."

  deploy:
    runs-on: ubuntu-latest
    needs: start-server
    # environment: production # Specify the production environment

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        # uses: Azure/login@v1
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}"
        # with:
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}
        #   enable-AzPSSession: true
        #   environment: azurecloud
        #   allow-no-subscriptions: false
        #   audience: api//AzureADTokenExchange
        #   auth-type: SERVICE_PRINCIPAL

      - name: Deploy to webapp
        # uses: azure/webapps-deploy@v2
        run: |
          echo "Deploying to Azure Web App... ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}"
        # with:
        #   app-name: "twactionsapp1"
        #   slot-name: "production"
        #   publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        #   package: "."

  # notify-teams:
  #   runs-on: ubuntu-latest
  #   needs: [deploy, test]
  #   if: always() # Always run this job to notify Teams
  #   steps:
  #     - name: Notify Teams
  #       uses: FreEZer00/teams-webhook-action@v1.4.1
  #       with:
  #         webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
  #         title: "Deployment Notification"
  #         job: ${{ toJson(needs)}}
